# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use latest version
    hooks:
      - id: trailing-whitespace
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 24.4.2  # Use latest Black release
    hooks:
      - id: black
